### PR TITLE
updated backgroundimage.jpg to be pcdm-trueos4k.jpg

### PR DESCRIPTION
**Pull request by mremski**
Simple copy of the trueos background jpg to the backgroundimage.jpg file.  That way, when you have autologin set in PCDM, you see TrueOS branding, not PC-BSD.

### CODE REVIEW

**Comment by q5sys** [comment]
Thanks for the PR!  I want to talk to Ken about this before merging, because I think we may want to instead work this into the different theme variants (tree/master/src-qt5/themes) so that it will use the appropriate image based on the system configuration.  It's be kinda silly to show the TrueOS jpg during auto login on an OpenBSD system.

**Comment by mremski** [comment]
No problem.  I was thinking either this or the default solid gray.  If I'm understanding the code over in pcdm correctly, if auto login was enabled, it'd show whatever was in backgroundimage.jpg (currently the PC BSD Joule background).

**Comment by q5sys** [comment]
If you want to change the image to the default grey that's in the default theme file, we can go ahead and merge this until Ken and I talk about reformatting the code to select the image file according to the overall theme.  The default grey that's logo-less will work in every situation since it's the background which all the themed wallpapers use as the backdrop.

**Comment by mremski** [comment]
Sounds good.  Updated to use themes/default/pcdm-default-4k.jpg for backgroundimage.jpg.  This uses the default gray instead of the PCBSD on an autologin setup.

**Comment by beanpole135** [comment]
Thanks for sending this in!
I just setup the loading/usage of the default wallpaper for the current theme for the auto-login dialog, but the blank/grey wallpaper you sent in will still be used as the fallback/default background.

Thanks!
https://github.com/trueos/pcdm/commit/2fa0247c45fb40c9d318568c88e5946164da0845

**Pull request merged**
